name: assignment
description: test app for interview


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  table_calendar: ^3.0.9

  # State management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Storage
  shared_preferences: ^2.1.2


  # Objects
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  collection: ^1.17.1

  # Architecture
  injectable: ^2.1.2
  get_it: ^7.6.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Styles
  google_fonts: ^5.0.0

  # Assets
  flutter_svg: ^2.0.7

dev_dependencies:
  injectable_generator:
  build_runner:
  flutter_gen_runner:
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0


flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_icon/app_icon.png"


flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon/app_icon.png

flutter:
  generate: true
  assets:
    - assets/images/no_employee/
    - assets/icons/
    - assets/images/app_icon/app_icon.png
    - assets/svg/
  uses-material-design: true
