name: assignment
description: test app for interview


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Storage
  hive: ^2.2.3

  # Objects
  freezed: ^2.3.5

  # Architecture
  injectable: ^2.1.2
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  flutter_gen_runner:
  freezed_annotation: ^2.2.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_icon/app_icon.png"


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon/app_icon.png

flutter:
  assets:
    - assets/images/no_employee/
    - assets/icons/
    - assets/images/app_icon/app_icon.png



  uses-material-design: true
